# Pinhole Camera Model Practice Questions

In [14]:
import math
import numpy as np

## Question 1: Perspective Projection

A 3D point in the camera coordinate system is given by `p_c = [10, 5, 20]`. 
The camera has a focal length `f` of 50mm. 
Calculate the position of the projection of this point on the image plane in meters.

In [9]:
f = 50/1000
p_c = [10,5,20]
u_m_c=(f)*(p_c[0]/p_c[2])
v_m_c=(f)*(p_c[1]/p_c[2])
print("u_m_c:")
print(u_m_c)
print("v_m_c:")
print(v_m_c)

u_m_c:
0.025
v_m_c:
0.0125


---

## Question 2: Conversion to Pixels

Given the projected point from Question 1, convert its coordinates from meters to pixels. 
Assume the following intrinsic parameters: 
- `s_x` = 800 pixels/meter
- `s_y` = 800 pixels/meter
- `o_x` = 320 pixels
- `o_y` = 240 pixels
What are the pixel coordinates `(u^I, v^I)`?

In [12]:
s_x=800
s_y=800
o_x=320
o_y=240
u_I=(s_x*u_m_c+o_x)
v_I=(s_y*v_m_c+o_y)
print("u_I:")
print(u_I)
print("v_I:")
print(v_I)

u_I:
340.0
v_I:
250.0


---

## Question 3: Intrinsic Matrix

Construct the intrinsic calibration matrix `K` using the parameters from Question 2, assuming no skew (`s_θ = 0`).

In [17]:
s_theta = 0
matrix = [[s_x*f,s_theta*f,o_x], [0,s_y*f,o_y],[0,0,1]]
K = np.array(matrix)
print(K)

[[ 40.   0. 320.]
 [  0.  40. 240.]
 [  0.   0.   1.]]


---

## Question 4: Point Projection with Known Pose

A point in the world frame is given by `p_w = [2, 3, 50]`. The camera's pose `T_w^c` is given by an identity rotation matrix and a translation vector `t_w^c = [0, 0, 10]`. [cite_start]Using the intrinsic matrix `K` from Question 3, calculate the pixel coordinates of the projected point. [cite: 14, 16, 17]

In [ ]:
p_w = np.array([[2],[3],[50],[1]])
T_w_c = np.array([[0],[0],[10]])
R_w_c = np.eye(3)
extrinsic = np.hstack([R_w_c, T_w_c])
two = (K @ extrinsic)
two.shape
two_p = (two @ p_w)
u_I = two_p[0]/two_p[2]
v_I = two_p[1]/two_p[2]
print("u_I: ", u_I)
print("v_I: ", v_I)

u_I:  [321.33333333]
v_I:  [242.]


---

## Question 5: Radial Distortion

A point is projected on the image plane at `(u_distort^I, v_distort^I) = (400, 350)` including radial distortion. Given distortion coefficients `a1 = 0.0001` and `a2 = 0.0000002` and the principal point `(o_x, o_y) = (320, 240)`, calculate the corrected pixel coordinates `(u^I, v^I)`.

In [74]:
a1 = 0.0001
a2 = 0.0000002
u_I = 400
v_I = 350
r_2 = (u_I-o_x)**2+(v_I-o_y)**2
u_I_corrected = (1+a1*r_2+a2*r_2**2)*(u_I-o_x)+o_x
v_I_corrected = (1+a1*r_2+a2*r_2**2)*(v_I-o_y)+o_y
print("u_I_corrected: ",u_I_corrected)
print("v_I_corrected: ",v_I_corrected)

u_I_corrected:  6024.0
v_I_corrected:  8083.0
